# Generated by Django 5.2.4 on 2025-07-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALX_week9_first_exercise_app', '0002_author_departments_student_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='food', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='is eatable'),
            preserve_default=False,
        ),
    ]
