# Generated by Django 5.2.4 on 2025-07-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALX_week9_first_exercise_app', '0003_remove_productdetail_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cource',
            name='student',
        ),
        migrations.AddField(
            model_name='cource',
            name='students',
            field=models.ManyToManyField(related_name='cources', to='ALX_week9_first_exercise_app.student'),
        ),
    ]
