# Generated by Django 5.2.4 on 2025-07-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALX_week9_first_exercise_app', '0004_remove_cource_student_cource_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cource',
            name='c_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
